// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlMsg = "OpenSession" | "CloseSession" | { "Session": string } | { "CreateKeyExpr": string } | { "KeyExpr": string } | { "DeleteKeyExpr": string } | { "DeclareSubscriber": [string, string] } | { "Subscriber": string } | { "UndeclareSubscriber": string } | { "DeclarePublisher": [string, string] } | { "Error": string };
