// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleWS } from "./SampleWS";

export type DataMsg = { "Sample": [SampleWS, string] } | { "PublisherPut": [Array<number>, string] };
