// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleKindWS } from "./SampleKindWS";

export type SampleWS = { key_expr: string, value: Array<number>, kind: SampleKindWS, };
