// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryReplyWS } from "./QueryReplyWS";
import type { QueryWS } from "./QueryWS";

export type QueryableMsg = { "Query": { queryable_uuid: string, query: QueryWS, } } | { "Reply": { reply: QueryReplyWS, } };
