// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryReplyVariant } from "./QueryReplyVariant";

export type QueryReplyWS = { query_uuid: string, result: QueryReplyVariant, };
