// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlMsg } from "./ControlMsg";
import type { DataMsg } from "./DataMsg";

export type RemoteAPIMsg = { "Data": DataMsg } | { "Control": ControlMsg };
