// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper";

export type ControlMsg =
  | "OpenSession"
  | "CloseSession"
  | { Session: string }
  | {
      Get: {
        key_expr: OwnedKeyExprWrapper;
        parameters: string | null;
        id: string;
      };
    }
  | { GetFinished: { id: string } }
  | { Put: { key_expr: OwnedKeyExprWrapper; payload: Array<number> } }
  | { Delete: { key_expr: OwnedKeyExprWrapper } }
  | { DeclareSubscriber: { key_expr: OwnedKeyExprWrapper; id: string } }
  | { Subscriber: string }
  | { UndeclareSubscriber: string }
  | {
      DeclarePublisher: {
        key_expr: OwnedKeyExprWrapper;
        encoding: string;
        congestion_control: number;
        priority: number;
        express: boolean;
        id: string;
      };
    }
  | { UndeclarePublisher: string }
  | {
      DeclareQueryable: {
        key_expr: OwnedKeyExprWrapper;
        complete: boolean;
        id: string;
      };
    }
  | { UndeclareQueryable: string };
