// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper";

export type QueryWS = { key_expr: OwnedKeyExprWrapper, parameters: string, encoding: string | null, attachment: Array<number> | null, payload: Array<number> | null, };
