// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryWS } from "./QueryWS";
import type { ReplyWS } from "./ReplyWS";

export type QueryableMsg = { "Query": { uuid: string, query: QueryWS, } } | { "Reply": { uuid: string, reply: ReplyWS, } };
